### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by keepeye** [nswbmw/koa-redis-pool#2]
TypeError: Cannot read property 'enqueue' of undefined
    at Object.acquire (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa-redis-pool/node_modules/generic-pool/lib/generic-pool.js:386:23)
    at /Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:136:8
    at Object.thunkToPromise (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:135:10)
    at Object.toPromise (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:119:55)
    at next (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:69:7)
    at /Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:54:5
    at Object.co (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:118:63)
    at next (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:69:7)
    at /Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:54:5
    at Object.co (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:118:63)
    at next (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:69:7)
    at /Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:54:5
    at Object.co (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:118:63)
    at next (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:69:7)
    at /Users/chengxianzhao/Documents/workspace/woyoo/cpa/api/node_modules/koa/node_modules/co/index.js:54:5

**Comment by nswbmw** [comment]
same as https://github.com/nswbmw/koa-mongo/issues/11
